### ISSUE TITLE
Thermostats set to "Off" shows target temperature to -20ºC

### ISSUE THREAD

**Issue by rikhudson** [asantaga/wiserHomeAssistantPlatform#11]
Any temperature set to "Off" (as part of Auto or Manual schedules shows the target temperature as -20ºC.

<img width="478" alt="screenshot 2019-01-04 at 11 50 03" src="https://user-images.githubusercontent.com/3898637/50686869-e4797200-1016-11e9-9110-9f557a739839.png">

_Sidenote: Thanks for all the great work on this, excited to see controls come in too!_ 🤞

**Comment by v966732** [comment]
You can use a template to amend the -20 value to zero e.g.:-
        value_template: >-
          {% if is_state_attr('climate.wiser_room','temperature', -20) %}
             0
          {% else %}
             {{state_attr('climate.wiser_room','temperature')}}
          {% endif %}

**Comment by asantaga** [comment]
Hey there

Yes this is a known issue.. If the rad is "Off" then I need to send something back , so I send -20.. I did toy with sending "0" back but that would be a valid value...., it might be zero degrees! whereas -20 was far out...

this is done by https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/climate/wiser.py lines 75.. The rads themselves are set to -3000!!!

You can override the -20 by setting the parameter `minimum:  ` 
e.g.
```
wiser:
  host: <ENTER YOUR HEATHUB IP HERE>
  password: <ENTER YOUR SECRET TOKEN, OBTAINED FROM STEP THREE HERE>
  scan_interval: 300
  minimum: -5
```
Is that ok, or can you think of a better solution?
