### ISSUE TITLE
[FR] Support Long Term Statistics

### ISSUE THREAD

**Issue by LucidityCrash** [asantaga/wiserHomeAssistantPlatform#153]
It would be good if the various Wiser sensors supported long term statistics 😀

**Comment by asantaga** [comment]
Yes. this is on the roadmap. I have another integration to lightwaveRF energy sensor where I can "cutting my teeth" and teting this this out on..

Alas Im moving house soon and really really time poor. My Wiser install is mostly removed (hub + 2 TRVs) so I dont have time to work on it right away but reading the docs it doesnt look difficult.

thanks for opening this ticket.

**Comment by msp1974** [comment]
I think at the minute LTS is only supported on sensors.  As such a climate entity (temp, heating setting etc) are not supported.  Could be wrong but cannot see state_class in anything but a sensor entity.  You can create a template sensor and set device_class = temperature and state_class = measurement.  Use the current_temperature value from the climate sensor and this will log LTS for room temp.

Is it temps that you were thinking of logging or something else?

**Comment by LucidityCrash** [comment]
sensor.wiser_heating and sensor.wiser_hot_water could be useful

**Comment by dunxd** [comment]
Sensors created within the template platform do not support state_class. That is what Check Configuration is telling me.

**Comment by wizmo2** [comment]
@dunxd you need to use the new template sensor format

```
template:
  - sensor:
      - unique_id: 'lounge_temperature'
        name: "Lounge Temperature"
        unit_of_measurement: '°C'
        device_class: 'temperature'
        state_class: 'measurement'
        state: "{{ state_attr('climate.wiser_lounge', 'current_temperature') }}"
```

**Comment by rlewis187** [comment]
This is what worked for me in my sensors.yaml file (after much trial & error as I really don't know what I'm doing:
`- platform: template
  sensors:
    jess_room_temp:
      friendly_name: "Wiser Jessicas Heating"
      unit_of_measurement: '°C'
      device_class: 'temperature'
      value_template: "{{ state_attr('climate.wiser_jessicas_heating', 'current_temperature') }}"`

**Comment by dunxd** [comment]
@rlewis187 that is what I already have in sensor.yaml but it doesn't allow using the statistics graph. Only the history graph.

@wizmo2 I tried using the format you suggest in my sensor.yaml but it just throws errors, so ended up with what @rlewis187 mentioned. I'm not sure if I am missing something in the documentation about a new format, or if a different syntax is needed for setting up template sensors in a single Vs spilt config. I'm confused.

**Comment by wizmo2** [comment]
@dunxd - it wont work in a sensor.yaml, needs to be in the configuration.yaml and 'template' at the root.    It takes an hour or two to get data, but I see mean / min / max on the LTS charts.

**Comment by dunxd** [comment]
@wizmo2 thanks. I didn't realise how much the difference there is between the old and new way of doing templates. 

Old way is setting up templates as a type of sensor (or binary sensor, etc).

New way is setting up sensors as a type of template. 

IMHO the HA documentation about templates doesn't really explain the different approaches, and how to migrate from one to the other.

Anyway, you helped me figure this out a bit! Many thanks.

**Comment by dunxd** [comment]
I finished adding my template sensors and now have them all working with the Statistics Graph/LTS.  I did it in a template.yaml file.

In configuration.yaml I have the line:

`template: !include template.yaml`

Here is a snippet from my template.yaml file showing how to add multiple template sensors in the new way:

```
- sensor:
    - unique_id: 'living_room_temperature_new'
      name: "New Living Room Temperature"
      unit_of_measurement: '°C'
      device_class: 'temperature'
      state_class: 'measurement'
      state: "{{ state_attr('climate.wiser_living_room', 'current_temperature')}}"
   - unique_id: 'hallway_temperature_new'
      name: "New Hallway Temperature"
      unit_of_measurement: '°C'
      device_class: 'temperature'
      state_class: 'measurement'
      state: "{{ state_attr('climate.wiser_hallway', 'current_temperature')}}"
```

The key values are device_class, state_class and unit_of_measurement.  If any of them are missing LTS won't work.

**Comment by wizmo2** [comment]
if you want to go crazy with templates, I'm working on getting an Energy sensor working.  You can add this as a Gas Consumption Source to get an estimate of energy use (although I still need to 'fudge' the fuel_flow to allow for demand and burner_on time not being the same)

```
template:
  - trigger:
      - platform: time_pattern
        # every 60s
        minutes: "*"
    sensor:
      - unique_id: 'wiser_energy'
        name: 'Wiser Energy'
        unit_of_measurement: "kWh"
        state_class: measurement
        device_class: energy
        state: > 
            {% set flow_rate = 2.25 | float %}
            {% set kerosene_energy = 10.35 | float %}
            {% set demand_value =  states('input_number.demand_percent') | float %} 
            {{ ( demand_value * flow_rate * kerosene_energy / 60) | round (2)  }}
        attributes:         
          last_reset: "{{ now () }}"

```
flow_rate is the burner flow rate per liter (I have an oil boiler)
kerosene_energy is kWh per liter

Need to do some more testing, but this seems to work the best of everything I tried so far (@dunxd - no help from HA documentation which is a total mess re. energy sensors and state_class right now!).
