### ISSUE TITLE
Boost service doesn't work without explicit temperature_delta

### ISSUE THREAD

**Issue by walshtj** [asantaga/wiserHomeAssistantPlatform#216]
The `boost_heating` service doesn't seem to work unless a `temperature_delta` is included now. It used to work without one and take the default value from the integration.

In the script below works but if I remove the `temperature_delta` entry it doesn't work.
I have a `default heating boost temperature` set in the integration at 2.
If I manually boost the heading from the lovelace widget it works fine also.
```
alias: Boost Bedroom
sequence:
  - service: wiser.boost_heating
    data:
      temperature_delta: 2
      time_period: 30
    target:
      entity_id:
        - climate.wiser_bedroom
mode: single
```
