### ISSUE TITLE
enable / disable schedules

### ISSUE THREAD

**Issue by diginfo** [asantaga/wiserHomeAssistantPlatform#296]
Apologies if this has been asked before, I spent the last 1/2 hour trying to figure it out but cant.

How can I enable a room schedule (i.e. "Follow Schedule" on the phone app) ?

I know I can get it's state with:

```
      value_template: {{ states('climate.wiser_living_room') == 'auto' }}
```

And these states are 'heat' (disabled) and 'auto' enabled But how can I enable / disable programmatically ?

**Comment by diginfo** [comment]
I can enable / disable water schedule no problem with:

```
    pac_wiser_water_auto:
      value_template: "{{ is_state('select.wiser_hot_water_mode', 'Auto') }}"
      turn_on:
        service: select.select_option
        data:
          option: Auto
        target:
          entity_id: select.wiser_hot_water_mode

      turn_off:
        service: select.select_option
        data:
          option: Manual
        target:
          entity_id: select.wiser_hot_water_mode

      icon_template: >-
        {% if is_state('select.wiser_hot_water_mode', 'Auto') %}
          mdi:refresh-auto
        {% else %}
          mdi:toggle-switch
        {% endif %}
```
