### ISSUE TITLE
Unable to cancel hotwater overrides with a template toggle switch

### ISSUE THREAD

**Issue by diginfo** [asantaga/wiserHomeAssistantPlatform#298]
I have setup a toggle switch to boost and disable boost for hot water.

If I call "button.wiser_cancel_hot_water_overrides" as a service from the developer page it works, but if I call my switch, it switches on but wont switch off and I get the following error:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:635
First occurred: 19:00:17 (2 occurrences)
Last logged: 19:01:26

Unable to find referenced entities button.wiser_cancel_hotwater_overrides or it is/they are currently not available
```

    
```
- platform: template
  switches:
    pac_wiser_heat_boost:
          value_template: "{{ state_attr('climate.wiser_living_room', 'is_boosted') == true }}"
          turn_on:
            service: button.press
            target:
              entity_id: button.wiser_boost_all_heating
              
          turn_off:
            service: button.press
            target:
              entity_id: button.wiser_cancel_hot_water_overrides
    
          icon_template: >-
            
            {% if state_attr('climate.wiser_living_room', 'is_boosted') == 'true' %}
              mdi:timer-plus
            {% else %}
              mdi:timer-cancel
            {% endif %}
```
