### ISSUE TITLE
Cannot create automation for switches/micromodules

### ISSUE THREAD

**Issue by belotv** [asantaga/wiserHomeAssistantPlatform#309]
Hi,
Automation menu only allow to create automation for heating related elements. This is too limiting in case we want to use a switch to trigger a micromodule for example. Would it be possible to add such support ? 

Kr

PS: this is quite "critical" because the current Wiser Home version does not support that function. Even the manual says a micromodule can be commanded by up to 10 switches but it seems that Schneider forgot to reimplement that in the current app so I am stuck at the moment and was hoping to find an alternate solution.

Valentin

**Comment by msp1974** [comment]
Hi,  I'm not really clear on the issue you have.  Are you saying you cannot use the integration switches in automations? If so, I'm not clear why calling the switch.turn_on service doesn't work.  Can you explain more.  Thanks

**Comment by belotv** [comment]
Hi, actually yesterday devices were not visible as devices but only as entities, only the heat platform (HubR) was visible as a device. This morning, everything was visible as devices, so I was able to create an automation. However, it is not really usable because it takes up to 10s to execute when triggered from the push button (3s when triggered from HA). Also it requires to have HA running. Isn't that possible to have automation stored in the hub ?

Automation script is :
```
alias: SDB
description: ""
trigger:
  - platform: device
    type: changed_states
    device_id: ae3bf0d5bcae2bd1c63f9369764e4e67
    entity_id: light.wiser_onofflight_sdb_interrupteur_sdb_light
    domain: light
condition: []
action:
  - type: toggle
    device_id: 1aba47eb752f190f6a8bc72a42a4ad40
    entity_id: light.wiser_onofflight_sdb_module_sdb_light
    domain: light
mode: single

```
