### ISSUE TITLE
set_schedule not working for old automation / some time entries changed to needing quotes

### ISSUE THREAD

**Issue by toddstar** [asantaga/wiserHomeAssistantPlatform#325]
More an fyi, as very easy to change on the users end, but it seems some time entries now need to be enclosed in quotes for the set_schedule file to correctly update the schedule and without updating your files to enclose the times in quote marks (see **File Fix** at the bottom) the old format fails silently. Couldn't see anything in release notes about this change, so mainly creating this just so others can find the information when searching for "set_schedule" issues to save themselves some debug/testing time.

e.g.
my spare room has the following code in my current saved files (I use node red to switch between 3 difference preset files for all my schedules based on the external temperature for a summer, winter & an inbetween sate)

```
Name: Wiser Top Room
Description: Schedule for Wiser Top Room
Type: Heating
Monday:
  - Time: 00:00
    Temp: 5.0
  - Time: 10:00
    Temp: 13.0
  - Time: 17:00
    Temp: 10.0
  - Time: 23:00
    Temp: 7.0
Tues.....
```

as its now getting cold enough that it should be switching between inbetween & winter I noticed that the schedule didn't seem to be changing and also couldn't see any errors being logged. So deleted the schedule from wiser, created a fresh dummy schedule in the wiser app and pulled it via get_schedule which output

```
Monday:
- Time: 06:30
  Temp: 5.0
- Time: 08:30
  Temp: 5.0
- Time: '22:30'
  Temp: 5.0
....
```
which now has quotes around 22:30 time but not the other times. (didn't test but guess its probably anything after 10:00???). Not sure when this changed but definitely post 'set_heating_schedule' changing to just 'set_schedule' as my old files still worked when testing the change to the service used

**File Fix**
All the time variables work enclosed so for a quick fix you can do a quick Ctrl+R (find & replace) to search for `Time: ` and replace all to `Time: '` and same with  `:00` to `:00'` /  `:15` to `:15'`  /  `:30` to `:30'` / etc.  

so that it looks something like below

```
Monday:
  - Time: '00:00'
    Temp: 5.0
  - Time: '10:00'
    Temp: 13.0
  - Time: '17:00'
    Temp: 10.0
  - Time: '23:00'
    Temp: 7.0
....
```
