### ISSUE TITLE
Error: No schedule exists for Wiser <room>

### ISSUE THREAD

**Issue by nottledim** [asantaga/wiserHomeAssistantPlatform#342]
I get this error when trying to use get_schedule service with the new schedule editor.  To workaround I have to load the room into the schedule editor, select edit for that room and save it.  After that get_schedule for that room works.

I don't know if this error recurs after a restart of Home Assistant.  I suspect it will.

My script for getting schedules calls get_schedule on all rooms.

**Comment by nottledim** [comment]
I'm not sure I can.  It seems to have been an initialisation issue that I can't reproduce. All rooms had/have schedules. It all works fine now as I hinted in original report. Also I've changed my script from:
```
wiser_schedules:
  alias: Wiser Schedules
  mode: single
  icon: mdi:clock-outline
  sequence:
  - service: wiser.get_schedule
    data:
      entity_id:
        - climate.wiser_dpbed
        - climate.wiser_dick
<all the rest>
```
to:
```
wiser_schedules:
  alias: Wiser Schedules
  mode: single
  icon: mdi:clock-outline
  sequence:
  - service: wiser.get_schedule
    data:
      filename: /config/wiser/dpbed.yaml
    target:
      entity_id: climate.wiser_dpbed
  - service: wiser.get_schedule
    data:
      filename: /config/wiser/dick.yaml
    target:
      entity_id: climate.wiser_dick
<all the rest>
```
and I did that because the first form uses directory config/schedules and I use config/wiser
I don't know now if that was the problem or is unrelated. I really can't remember.   It seems like 3 months ago I reported this, not 3 weeks :-)

I think it might be best to close this pending anybody else encountering the problem.
