### ISSUE TITLE
Humdity read numerical state for automation

### ISSUE THREAD

**Issue by colany1** [asantaga/wiserHomeAssistantPlatform#402]
Hello,
can't make automation based on the numeric_state  triguer of humidity. ( start fan )

platform: numeric_state
entity_id:
  - climate.wiser_salon
attribute: current_humidity
above: 55

---> don"t work

platform: device
device_id: d33223eae5495db17328d5128ae607b2
domain: climate
entity_id: 02a38166d0ba027543b60abe35ea2c5f
type: current_humidity_changed
above: 55

---->don't work

platform: numeric_state
entity_id:
  - sensor.wiser_lts_humidity_salon
attribute: humidty
above: 55

---->don't work

etc.....

could you help ?
thanks !!!

**Comment by msp1974** [comment]
I setup an automation to test this when seeing your issue.  However, it works fine.  Did you resolve it.  My automation is below:

```yaml
alias: Humidity Test Automation
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - climate.wiser_office
    attribute: current_humidity
    above: 50
  - platform: numeric_state
    entity_id:
      - sensor.wiser_lts_humidity_office
    above: 50
condition: []
action:
  - service: notify.persistent_notification
    data:
      message: Humidity above 50
mode: single
```
