### ISSUE TITLE
Add icons to new thermostat card "climate-preset-modes"

### ISSUE THREAD

**Issue by codemunkie15** [asantaga/wiserHomeAssistantPlatform#414]
Hi

Would it be possible to change the icons on the new thermostat card "climate-preset-modes" feature please? They currently show as a dot icon and there doesn't seem to be any way to change them via yaml.

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/13065317/dfeacee0-2456-4d6e-b0e7-a9d64533b870)

```
- type: thermostat
  entity: climate.wiser_office
  name: "Office"
  features:
    - type: "climate-hvac-modes"
      hvac_modes:
        - auto
        - heat
        - "off"
    - type: "climate-preset-modes"
      style: "icons"
      preset_modes:
        - "Cancel Overrides"
        - "Boost 30m"
        - "Boost 1h"
        - "Boost 2h"
        - "Boost 3h"
```
