### ISSUE TITLE
The unit of sensor.wiser_lts [...] (°C) cannot be converted to the unit of previously compiled statistics (None).

### ISSUE THREAD

**Issue by Chaoscontrol** [asantaga/wiserHomeAssistantPlatform#434]
For a while now I've been getting these types of warnings in the HA log. Usually once every day or so. 

```
The unit of sensor.wiser_lts_target_temperature_main_bedroom (°C) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
```
I'm not sure if it's always the same sensor or it keeps changing. I usually just follow the instructions and apply the "fix" as instructed. But that only solves the issue temporarily, until the warning shows up again. 
I'm pretty sure the unit keeps getting changed from `None` to `C`, and then back again. Which repeatedly triggers the warning even after it being fixed. 

Which led me to believe there is an actual issue with the integration. It's been happening for weeks if not months, over updates as well. 

Integration v3.4.2.
HA:
```
Core
2024.1.6
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0
```
HubR, with single channel, on a combi boiler without OpenTherm. Firm 3.14.0.

**Comment by msp1974** [comment]
Can you tell me if there are any automations or things that you do (such as turning off heating etc) in that room.

**Comment by Chaoscontrol** [comment]
It's just an example room, as I said, it's not always the same one. 

There are no automations at all with any of the room devices. Only a single automation within the hub itself, to switch the away mode based on geolocation. I don't think this is related. This triggers about once a week as we work from home, and it just toggles the thing. 

Here it is:
```
alias: Home Proximity
description: ""
trigger:
  - platform: numeric_state
    entity_id: proximity.home
    above: 3
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: away
  - platform: numeric_state
    entity_id: proximity.home
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: near-home
    below: 3
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: away
        sequence:
          - type: turn_on
            device_id: 8f7b3c13e63e5fd07bcad676d0f76ca8
            entity_id: switch.wiser_away_mode
            domain: switch
          - service: light.turn_off
            data: {}
            target:
              entity_id: all
          - service: notify.mobile_app_xiaomi_12_lite_ax
            data:
              title: Everyone left home
              message: "Heating and lights switched off. "
      - conditions:
          - condition: trigger
            id: near-home
        sequence:
          - type: turn_off
            device_id: 8f7b3c13e63e5fd07bcad676d0f76ca8
            entity_id: switch.wiser_away_mode
            domain: switch
          - device_id: 255599bab4f8d77d4b7f2ff74dc494a1
            domain: mobile_app
            type: notify
            message: "Heating switched to schedule. "
            title: Someone is heading home.
mode: single
```
