### ISSUE TITLE
Wiser Overview Card cannot be implemented in another card

### ISSUE THREAD

**Issue by pdoubleyou** [asantaga/wiserHomeAssistantPlatform#522]
This may be a fault between my brain and my mouse, but here goes. On my overview there is a card for each Wiser area that shows a  temperature gauge and buttons for Auto, Heat and Off. I try to emulate this on a new card and do not get the same card. 
![image](https://github.com/user-attachments/assets/78804440-5ec0-49f3-96cc-7c4ef4ed6355) Is what I want but cannot seem to emulate this on a new page.  I dont have the knowhow to pick out the relevant yaml to do this.

**Comment by asantaga** [comment]
This is my one

![image](https://github.com/user-attachments/assets/09a1deab-3944-4f94-90a8-f4755637bac4)

The Yaml is 
```
type: thermostat
entity: climate.wiser_lounge
features:
  - type: climate-hvac-modes
    hvac_modes:
      - auto
      - heat
      - "off"

```

to add this one, I selected the entity using "climate.xxx" and HA chose this card. For my house however Ive switched the more smaller mini climate cards
