### ISSUE TITLE
Is it possible to rename individual elements in a history-graph

### ISSUE THREAD

**Issue by DrJohnT** [asantaga/wiserHomeAssistantPlatform#72]
I added some history-graphs to my Lovelace interface which show the pattern the heat hub takes in  heating a room.  These look pretty awesome.  However, I was wondering if there was anyway to change the names if the three lines.  In the attached screenshot, the entity is called climate.wiser_upstairs, so the legend has very long names such as "Wiser Upstairs Current Temperature", "Wiser Upstairs Heating" and "Wiser Upstairs target Temperature".  Is there anyway to override / shorten these names?  

![History Graph - Wiser Upstairs](https://user-images.githubusercontent.com/10464775/75351208-ac2e9600-589f-11ea-8f18-df128430ef82.png)

BTW I absolutely adore this extension for Home Assistant.  Awesome work!  I plan to publish my config and screenshots once I have my Lovelace interface fully sorted out.

**Comment by asantaga** [comment]
I think HA allows you to rename sensors etc.. but Ive not tried it.. When I finish work (yeah still working - coding java now), I'll have a look.

If you come up with some nice graphs etc, let me know and I'll add them as recipies to the repo.

**Comment by DrJohnT** [comment]
Actually I found a solution this morning. Simply adding an override of the to the entity in the Lovelace UI does the trick.  (i.e. the name: Upstairs bit below).  

```yaml
entities:
  - entity: climate.wiser_upstairs
    name: Upstairs
hours_to_show: 12
refresh_interval: 0
title: Upstairs Heating
type: history-graph
```

So now they read "Upstairs current temperature", "Upstairs heating" and "Upstairs target temperature".  Still a little long, so I tried a space character and that works although the "c" in "current " is in lowercase :-(

```yaml
entities:
  - entity: climate.wiser_upstairs
    name: ' '
hours_to_show: 12
refresh_interval: 0
title: Upstairs Heating
type: history-graph
```

It would be nice to be able to give them the names "Current", "Heating" and "Target" as the "temperature" bit is redundant given the chart title.

**Comment by asantaga** [comment]
Hey @DrJohnT 

I just checked the code and I dont think we put the word "temperature" at the end, we do put Wiser at the beginning though

climate.py , lines 258-260

```
    @property
    def name(self):
        return "Wiser " + self.data.wiserhub.getRoom(self.room_id).get("Name")
``` 

Im guessing the HA Climate entity is adding temperature to the end.. 

Good that a workaround is available though. 

1. Should we remove the "Wiser " at the front? I think that might be a little redundant given the sensor is of type "wiser"?
2. Make sure you are using the lovelace history graph, I noted that the states one is going away (see https://community.home-assistant.io/t/what-will-replace-the-history-graph-after-its-deprecated-0-107-0/171863)
3. For graphs I dont use the history graph but I put the data into influxDB and then use grafana, WAY more useful as I can see data covering months/years

e.g.

![image](https://user-images.githubusercontent.com/2940224/75436409-68de3100-594c-11ea-93d0-56f302951a78.png)

to be honest this is why I originally built the extension :-)

I'll add your hint/tip re history graph to the readme soon, 
leaving open for now

**Comment by msp1974** [comment]
@DrJohnT the other way to do this (if you want your names to be as you say) is to create template sensors from the attributes of the climate sensor.  Example as below.

`sensor:

  - platform: template
    sensors:
      lounge_current_temp:
        friendly_name: "Current"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.wiser_lounge','current_temperature')}}"
        
      lounge_target_temp:
        friendly_name: "Target"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.wiser_lounge','temperature')}}"
        
      lounge_heating:
        friendly_name: "Heating"
        value_template: "{{ state_attr('climate.wiser_lounge','control_output_state')}}"`

**Comment by msp1974** [comment]
@DrJohnT the other way to do this (if you want your names to be as you say) is to create template sensors from the attributes of the climate sensor.  Example as below.


```
sensor:
  - platform: template
    sensors:
      lounge_current_temp:
        friendly_name: "Current"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.wiser_lounge','current_temperature')}}"
        
      lounge_target_temp:
        friendly_name: "Target"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('climate.wiser_lounge','temperature')}}"
        
      lounge_heating:
        friendly_name: "Heating"
        value_template: "{{ state_attr('climate.wiser_lounge','control_output_state')}}"
```
The you can add all 3 entities to your history graph and they will be named as per the friendly names above.
