### ISSUE TITLE
wiser_heating sensor

### ISSUE THREAD

**Issue by phixion** [asantaga/wiserHomeAssistantPlatform#74]
I'm trying to determine how many hour's per week my heating is on so I was writing template sensors (in HA) around the wiser_heating sensor. However, it seems I'm misunderstanding the purpose of that sensor or its not reporting correctly as it's only changing state to 'true' when I manually override heating. When heating turns on via schedule (from the wiser-app) it stays 'off'. I tried to integrate my idea via the iTRVS but I realized they dont change states when on a schedule, they are just on "auto". 

Also it seems to be always reporting all rooms to be in heating mode, but I havent looked into that very much yet.

Whats that sensor for?

Possible workaround could be transfering the schedule to HA and write automations, but the app is alright and integrates very good into google home. Another idea is pulling their heat-report via the api

**Comment by Fulch** [comment]
Do you have a 1 or 2 channel heating system?
Have you tried viewing the sensor on the Developer Tools > States page?

The "sensor.wiser_heating" on my system shows 'on' when the Wiser hub is calling for heat from the boiler, this happens if it's turned on by schedule or manually. It may take a minute or two to update when the boiler switches on or off but I can see the value change in the state column.

The TRV's have an attribute called 'control_output_state' which will also show 'on' or 'off' but you would of course need to make a template sensor to make use of this value.

**Comment by phixion** [comment]
Hmm, seems I do not have that attribute on my TRVs :(

https://i.phx.ms/bZr8.png

I guess my only option left is to have HA handle the schedule and do something like:

```
- platform: history_stats
  name: history_stats_climate_flur
  entity_id: climate.wiser_flur
  state: 'heat'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
```

**Comment by Fulch** [comment]
Sorry, my description was not accurate, it's an attribute of the 'climate entity' for the room that contains the TRV or Roomstat. Notice that the 'control_output_state' is 'On'.
You should have a 'climate entity' for each room that contains either a TRV or a Roomstat, by using a template sensor you can then make use of this attribute to calculate the running time for each room.

![image](https://user-images.githubusercontent.com/26844642/75629573-0189e080-5bdb-11ea-8b3b-4887bcaf5e3f.png)

This is the wiser sensor on my system showing heating is 'On'. I think it would be much easier to use this sensor value to calculate your total hours running time, I'm not sure why your system does not seem to update this sensor correctly.

![image](https://user-images.githubusercontent.com/26844642/75629758-845f6b00-5bdc-11ea-8571-25c2175bf48d.png)

**Comment by phixion** [comment]
How did I always miss that attribute? Thanks!

Thats how it looks for me the pas couple of hours https://i.phx.ms/wnrC.png

**Comment by Fulch** [comment]
I'm glad you found it!! Turn the heating on and watch your gas bill rise :😄

**Comment by asantaga** [comment]
Nice guys!

@phixion , can I ask you do document this for me and I'll add it to the repository as a "cookbook?" Either send it to me as a thread reply below or create a pull request


Do this by pushing all my HA data to InfluxDB and the graph it out using Grafana.. 

Mine looks like this

![image](https://user-images.githubusercontent.com/2940224/75634605-2ac06600-5c07-11ea-90cb-cec8e5521e17.png)

I have some missing data because my router went wonky....

**Comment by phixion** [comment]
sure, will do tomorrow! I'm kinda busy today

**Comment by phixion** [comment]
Since I cannot find the cookbook. here's an example config for a room called "Flur"

binary_sensor.yaml: sensor to check if heating is turned on or off, also sets a suiting icon:

```
- platform: template
    heating_flur:
      friendly_name: Heating Flur
      value_template: '{{state_attr("climate.wiser_flur","control_output_state") == "On"}}'
      icon_template: >-
        {% if is_state("binary_sensor.heating_flur", "on") %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}
```
sensor.yaml: history_stat sensor **for today** utilizing the binary sensor from above
```
- platform: history_stats
  name: Heating Flur On Today
  entity_id: binary_sensor.heating_flur
  state: 'on'
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"
```
sensor.yaml: history_stat sensor **for yesterday** utilizing the binary sensor from above

```
- platform: history_stats
  name: Heating Flur On Yesterday
  entity_id: binary_sensor.heating_flur
  state: 'on'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24
```
sensor.yaml: history_stat sensor **for this week so far** utilizing the binary sensor from above

```
- platform: history_stats
  name: Heating Flur On this Week
  entity_id: binary_sensor.heating_flur
  state: 'on'
  type: time
  start: "{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}"
  end: "{{ now() }}"
```
sensor.yaml: history_stat sensor **for the past 30 days** utilizing the binary sensor from above
```
- platform: history_stats
  name: Heating Flur On past 30 days
  entity_id: binary_sensor.heating_flur
  state: 'on'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 30
```
sensors.yaml: history_stats spits out unitof measuerment in hours, so here is a simple converion:

```
- platform: template
  sensors:
    heating_time_flur:
      friendly_name: Heating Time Flur
      icon_template: mdi:radiator
      value_template: "{{ states('sensor.heating_flur_on_today') | float * 60 }}"
      unit_of_measurement: min
```
