### ISSUE TITLE
Switching hot water on does not work in scripts

### ISSUE THREAD

**Issue by DrJohnT** [asantaga/wiserHomeAssistantPlatform#87]
Odd bug, but calling wiser.set_hotwater_mode / hotwater_mode: on in the developer tools works, but doing the same in scripts does not.  What am I doing wrong?

This works:
![1_ThisWorks](https://user-images.githubusercontent.com/10464775/78236888-887bf280-74d2-11ea-9ba8-2a7c745e516c.png)

This does not:
![2_ThisDoesNot](https://user-images.githubusercontent.com/10464775/78236914-8fa30080-74d2-11ea-9fd2-ff4439039df7.png)

```yaml
script:
  # Hot Water On
  wiser_hot_water_on:
    alias: 'Wiser: Hot Water On'
    sequence:
    - service: wiser.set_hotwater_mode
      data:
        hotwater_mode: on
```

**Comment by asantaga** [comment]
I cant test it now but anything in the logs?

**Comment by DrJohnT** [comment]
Nothing in the HA logs.   Is there a specific log for wiser?  Or an object for the wiser integration I can add to logger config?

I just upgraded to v2.1 - but reported this before the upgrade.  Same issue on latest code base.

**Comment by msp1974** [comment]
Add custom_components.wiser: debug to logger logs in config.yaml to see all debug logging.

**Comment by asantaga** [comment]
I just tested it here from Services and Scripts and it appears to work fine..

I configured the script using the UI, instead of YAML and then fired it from HA 

My script looks like this
```
'1585902280452':
  alias: testHW
  sequence:
  - data:
      hotwater_mode: 'on'
    service: wiser.set_hotwater_mode
~
```
