### ISSUE TITLE
Request - Humidity

### ISSUE THREAD

**Issue by majones319** [asantaga/wiserHomeAssistantPlatform#96]
Hi. The room thermostats measure humidity. Is it possible to show the values? Thanks.

**Comment by m01** [comment]
Yes, you can see it if you click on the RoomStat.

If you want it displayed separately, you can do something like this today:

```
sensor:
# relative humidity
  - platform: template
    sensors:
      wiser_roomstat_my_room_humidity:
        entity_id: sensor.wiser_roomstat_my_room
        friendly_name_template: "{{ states.sensor.wiser_roomstat_my_room.name }} Humidity"
        value_template: '{{ state_attr("sensor.wiser_roomstat_my_room", "humidity") }}'
        unit_of_measurement: '%'
```

I was wondering whether this might be more useful value to display compared to the reception (my roomstat doesn't move much), but I guess it depends on the use-case.
